name: Java Maven Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Maven tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Run tests
        working-directory: flow-diff
        run: mvn test

